<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Overtime Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
        }
        .header h1 {
            margin: 0;
            font-size: 18px;
            text-transform: uppercase;
        }
        .header p {
            margin: 5px 0;
            color: #666;
        }
        .meta {
            margin-bottom: 15px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #f4f4f4;
            font-weight: bold;
        }
        .status-approved { color: green; }
        .status-pending { color: orange; }
        .status-rejected { color: red; }
        .footer {
            position: fixed;
            bottom: 0;
            width: 100%;
            text-align: center;
            font-size: 10px;
            color: #999;
            border-top: 1px solid #ddd;
            padding-top: 10px;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ config('app.name') }}</h1>
        <p>Overtime Report</p>
    </div>

    <div class="meta">
        <strong>Period:</strong> {{ \Carbon\Carbon::parse($startDate)->format('d M Y') }} - {{ \Carbon\Carbon::parse($endDate)->format('d M Y') }}<br>
        <strong>Generated:</strong> {{ now()->format('d M Y H:i') }}
    </div>

    <table>
        <thead>
            <tr>
                <th>Date</th>
                <th>Employee</th>
                <th>Time</th>
                <th>Duration</th>
                <th>Reason</th>
                <th>Status</th>
                <th>Approver</th>
            </tr>
        </thead>
        <tbody>
            @forelse($overtimes as $overtime)
                <tr>
                    <td>{{ \Carbon\Carbon::parse($overtime->date)->format('d/m/Y') }}</td>
                    <td>{{ $overtime->user->name }}</td>
                    <td>{{ \Carbon\Carbon::parse($overtime->start_time)->format('H:i') }} - {{ \Carbon\Carbon::parse($overtime->end_time)->format('H:i') }}</td>
                    <td>{{ $overtime->duration }} mins</td>
                    <td>{{ $overtime->reason }}</td>
                    <td>
                        @if($overtime->status === 'approved')
                            <span class="status-approved">Approved</span>
                        @elseif($overtime->status === 'pending')
                            <span class="status-pending">Pending</span>
                        @else
                            <span class="status-rejected">{{ ucfirst($overtime->status) }}</span>
                        @endif
                    </td>
                    <td>{{ $overtime->approver ? $overtime->approver->name : '-' }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="7" style="text-align: center;">No overtime records found for this period.</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">
        Generated by {{ config('app.name') }} System
    </div>
</body>
</html>
